// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3H2YOwvt5lsy1BErugZNlkJhzu6-LWcU',
    appId: '1:170979659733:web:4b60f776744886dfec775c',
    messagingSenderId: '170979659733',
    projectId: 'task-manager-85faf',
    authDomain: 'task-manager-85faf.firebaseapp.com',
    storageBucket: 'task-manager-85faf.firebasestorage.app',
    measurementId: 'G-X26CLV20GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAB3tgFHldyjpMngLXIsvPkHo45_NeYow',
    appId: '1:170979659733:android:d84b802e215544afec775c',
    messagingSenderId: '170979659733',
    projectId: 'task-manager-85faf',
    storageBucket: 'task-manager-85faf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqHJ3XuEGcXcFRVRl3wgPfdlrvViMOvwo',
    appId: '1:170979659733:ios:00cf632c66af2702ec775c',
    messagingSenderId: '170979659733',
    projectId: 'task-manager-85faf',
    storageBucket: 'task-manager-85faf.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqHJ3XuEGcXcFRVRl3wgPfdlrvViMOvwo',
    appId: '1:170979659733:ios:00cf632c66af2702ec775c',
    messagingSenderId: '170979659733',
    projectId: 'task-manager-85faf',
    storageBucket: 'task-manager-85faf.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3H2YOwvt5lsy1BErugZNlkJhzu6-LWcU',
    appId: '1:170979659733:web:5796144809bd56d4ec775c',
    messagingSenderId: '170979659733',
    projectId: 'task-manager-85faf',
    authDomain: 'task-manager-85faf.firebaseapp.com',
    storageBucket: 'task-manager-85faf.firebasestorage.app',
    measurementId: 'G-TX86B6D8P2',
  );
}
